In [13]:
from datetime import datetime
import pandas as pd
from pathlib import Path

import pyam

In [2]:
connection = pyam.iiasa.Connection("ngfs_phase_5_internal")

[INFO] 10:57:30 - ixmp4.conf.settings: Connecting as user 'huppmann'.
[INFO] 10:57:31 - pyam.iiasa: You are connected to the IXSE_NGFS_PHASE_5_INTERNAL scenario explorer hosted by IIASA. If you use this data in any published format, please cite the data as provided in the explorer guidelines: https://data.ene.iiasa.ac.at/ngfs-phase-5-internal/#/about
[INFO] 10:57:31 - pyam.iiasa: You are connected as user `huppmann`

In [38]:
scenario_mapping = {
    "o_2c": "Below 2°C",
    "o_1p5c": "Net-Zero 2050",
    "d_delfrag": "Delayed Transition",
    "d_strain": "Fragmented World",
    "h_cpol": "Current Policies",
    "h_ndc": "Nationally Determined Contributions (NDCs)",
    "o_lowdem": "Low Demand",
    "forecast baseline": "Baseline",
}

In [49]:
runs = connection.properties(
    default_only=False,
    model=["GCAM 6.0 NGFS", "MESSAGEix-GLOBIOM 2.0-M-R12-NGFS", "REMIND-MAgPIE 3.3-4.8"],
    scenario=scenario_mapping.keys(), 
)

In [50]:
runs

                                            scheme  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag     NaN
                                 d_strain      NaN
                                 h_cpol        NaN
                                 o_1p5c        NaN
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem      NaN
...                                            ...
                                 o_1p5c        NaN
                                 h_ndc         NaN
                                 o_2c          NaN
                                 h_cpol        NaN
                                 h_cpol        NaN

                                                                                   annotation  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag  Imported from file /work/process/jeedir/ngfs_p...
                                 d_strain   Imported from file /work/process/jeedir/ngfs_p...
                                 h_cpol     Imported from file /work/process/jeedir/ngfs_p...
                                 o_1p5c     Imported from file /work/process/jeedir/ngfs_p...
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem   Imported from file /work/process/jeedir/ngfs_p...
...                                                                                       ...
                                 o_1p5c     Imported from file /work/process/jeedir/ngfs_p...
                                 h_ndc      Imported from file /work/process/jeedir/ngfs_p...
                                 o_2c       Imported from file /work/process/jeedir/ngfs_p...
                                 h_cpol     Imported from file /work/process/jeedir/ngfs_p...
                                 h_cpol     Imported from file /work/process/jeedir/ngfs_p...

                                                                                     metadata  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag  {'p83 peak warming (MAGICCv7.5.3)': 2.20453232...
                                 d_strain   {'p83 peak warming (MAGICCv7.5.3)': 2.92450717...
                                 h_cpol     {'p83 peak warming (MAGICCv7.5.3)': 3.58103986...
                                 o_1p5c     {'p83 peak warming (MAGICCv7.5.3)': 2.04033624...
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem                                                  {}
...                                                                                       ...
                                 o_1p5c     {'p83 peak warming (MAGICCv7.5.3)': 1.99492591...
                                 h_ndc      {'p83 peak warming (MAGICCv7.5.3)': 2.49792487...
                                 o_2c       {'p83 peak warming (MAGICCv7.5.3)': 2.14547379...
                                 h_cpol     {'p83 peak warming (MAGICCv7.5.3)': 3.31744871...
                                 h_cpol     {'p83 peak warming (MAGICCv7.5.3)': 3.31744871...

                                            run_id  model_id  scen_id  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag       8         2        1
                                 d_strain        9         2        2
                                 h_cpol         10         2        3
                                 o_1p5c         11         2        5
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem       65        41        7
...                                            ...       ...      ...
                                 o_1p5c       1004        41        5
                                 h_ndc        1005        41        4
                                 o_2c         1006        41        6
                                 h_cpol       1007        41        3
                                 h_cpol       1021        41        3

                                            is_default  is_locked create_user  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag       False      False     bertram
                                 d_strain        False      False     bertram
                                 h_cpol          False      False     bertram
                                 o_1p5c          False      False     bertram
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem        False      False         min
...                                                ...        ...         ...
                                 o_1p5c           True      False    yiyi_git
                                 h_ndc            True      False    yiyi_git
                                 o_2c             True      False    yiyi_git
                                 h_cpol          False      False    yiyi_git
                                 h_cpol           True      False   hackstock

                                                           create_date  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag  2024-03-01 22:42:46.000000
                                 d_strain   2024-03-01 22:43:14.000000
                                 h_cpol     2024-03-01 22:43:39.000000
                                 o_1p5c     2024-03-01 22:44:03.000000
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem   2024-03-18 14:07:43.000000
...                                                                ...
                                 o_1p5c     2025-05-28 14:01:30.000000
                                 h_ndc      2025-05-28 14:06:57.000000
                                 o_2c       2025-05-28 14:12:28.000000
                                 h_cpol     2025-05-28 14:17:54.000000
                                 h_cpol     2025-06-17 16:15:11.000000

                                            update_user  update_date  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag          NaN          NaN
                                 d_strain           NaN          NaN
                                 h_cpol             NaN          NaN
                                 o_1p5c             NaN          NaN
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem           NaN          NaN
...                                                 ...          ...
                                 o_1p5c             NaN          NaN
                                 h_ndc              NaN          NaN
                                 o_2c               NaN          NaN
                                 h_cpol             NaN          NaN
                                 h_cpol             NaN          NaN

                                            lock_user  lock_date  version
model                            scenario
GCAM 6.0 NGFS                    d_delfrag        NaN        NaN        1
                                 d_strain         NaN        NaN        1
                                 h_cpol           NaN        NaN        1
                                 o_1p5c           NaN        NaN        1
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem         NaN        NaN        1
...                                               ...        ...      ...
                                 o_1p5c           NaN        NaN       20
                                 h_ndc            NaN        NaN       19
                                 o_2c             NaN        NaN       16
                                 h_cpol           NaN        NaN       18
                                 h_cpol           NaN        NaN       19

[229 rows x 15 columns]

In [51]:
runs.create_date = pd.to_datetime(runs.create_date, yearfirst=True)

In [53]:
release_runs = runs[runs.create_date < datetime(2024, 11, 4)]

In [54]:
release_runs

                                            scheme  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag     NaN
                                 d_strain      NaN
                                 h_cpol        NaN
                                 o_1p5c        NaN
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem      NaN
...                                            ...
                                 o_lowdem      NaN
                                 h_ndc         NaN
                                 d_strain      NaN
                                 d_delfrag     NaN
                                 o_lowdem      NaN

                                                                                   annotation  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag  Imported from file /work/process/jeedir/ngfs_p...
                                 d_strain   Imported from file /work/process/jeedir/ngfs_p...
                                 h_cpol     Imported from file /work/process/jeedir/ngfs_p...
                                 o_1p5c     Imported from file /work/process/jeedir/ngfs_p...
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem   Imported from file /work/process/jeedir/ngfs_p...
...                                                                                       ...
                                 o_lowdem   Imported from file /work/process/jeedir/ngfs_p...
                                 h_ndc      Imported from file /work/process/jeedir/ngfs_p...
                                 d_strain   Imported from file /work/process/jeedir/ngfs_p...
                                 d_delfrag  Imported from file /work/process/jeedir/ngfs_p...
                                 o_lowdem   Imported from file /work/process/jeedir/ngfs_p...

                                                                                     metadata  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag  {'p83 peak warming (MAGICCv7.5.3)': 2.20453232...
                                 d_strain   {'p83 peak warming (MAGICCv7.5.3)': 2.92450717...
                                 h_cpol     {'p83 peak warming (MAGICCv7.5.3)': 3.58103986...
                                 o_1p5c     {'p83 peak warming (MAGICCv7.5.3)': 2.04033624...
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem                                                  {}
...                                                                                       ...
                                 o_lowdem   {'p83 peak warming (MAGICCv7.5.3)': 2.00666148...
                                 h_ndc      {'p83 peak warming (MAGICCv7.5.3)': 2.49792487...
                                 d_strain   {'p83 peak warming (MAGICCv7.5.3)': 2.59918554...
                                 d_delfrag  {'p83 peak warming (MAGICCv7.5.3)': 2.22652781...
                                 o_lowdem   {'p83 peak warming (MAGICCv7.5.3)': 2.00666148...

                                            run_id  model_id  scen_id  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag       8         2        1
                                 d_strain        9         2        2
                                 h_cpol         10         2        3
                                 o_1p5c         11         2        5
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem       65        41        7
...                                            ...       ...      ...
                                 o_lowdem      792        41        7
                                 h_ndc         807        41        4
                                 d_strain      808        41        2
                                 d_delfrag     809        41        1
                                 o_lowdem      810        41        7

                                            is_default  is_locked create_user  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag       False      False     bertram
                                 d_strain        False      False     bertram
                                 h_cpol          False      False     bertram
                                 o_1p5c          False      False     bertram
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem        False      False         min
...                                                ...        ...         ...
                                 o_lowdem        False      False    yiyi_git
                                 h_ndc           False      False   hackstock
                                 d_strain        False      False   hackstock
                                 d_delfrag       False      False   hackstock
                                 o_lowdem        False      False   hackstock

                                                   create_date  update_user  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag 2024-03-01 22:42:46          NaN
                                 d_strain  2024-03-01 22:43:14          NaN
                                 h_cpol    2024-03-01 22:43:39          NaN
                                 o_1p5c    2024-03-01 22:44:03          NaN
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem  2024-03-18 14:07:43          NaN
...                                                        ...          ...
                                 o_lowdem  2024-07-25 13:11:19          NaN
                                 h_ndc     2024-07-29 11:19:05          NaN
                                 d_strain  2024-07-29 11:28:00          NaN
                                 d_delfrag 2024-07-29 11:32:47          NaN
                                 o_lowdem  2024-07-29 11:37:30          NaN

                                            update_date  lock_user  lock_date  \
model                            scenario
GCAM 6.0 NGFS                    d_delfrag          NaN        NaN        NaN
                                 d_strain           NaN        NaN        NaN
                                 h_cpol             NaN        NaN        NaN
                                 o_1p5c             NaN        NaN        NaN
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem           NaN        NaN        NaN
...                                                 ...        ...        ...
                                 o_lowdem           NaN        NaN        NaN
                                 h_ndc              NaN        NaN        NaN
                                 d_strain           NaN        NaN        NaN
                                 d_delfrag          NaN        NaN        NaN
                                 o_lowdem           NaN        NaN        NaN

                                            version
model                            scenario
GCAM 6.0 NGFS                    d_delfrag        1
                                 d_strain         1
                                 h_cpol           1
                                 o_1p5c           1
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem         1
...                                             ...
                                 o_lowdem        15
                                 h_ndc           16
                                 d_strain        14
                                 d_delfrag       13
                                 o_lowdem        16

[185 rows x 15 columns]

In [55]:
for (model, scenario), i in release_runs.groupby(["model", "scenario"]):
    print(model, scenario, max(i.version), max(i.create_date))

GCAM 6.0 NGFS d_delfrag 9 2024-06-28 09:30:04
GCAM 6.0 NGFS d_strain 9 2024-06-28 09:30:21
GCAM 6.0 NGFS h_cpol 9 2024-06-28 09:30:38
GCAM 6.0 NGFS h_ndc 8 2024-06-28 09:30:54
GCAM 6.0 NGFS o_1p5c 9 2024-06-28 09:31:11
GCAM 6.0 NGFS o_2c 8 2024-06-28 09:31:29
GCAM 6.0 NGFS o_lowdem 8 2024-07-12 03:53:54
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS d_delfrag 13 2024-07-29 11:32:47
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS d_strain 14 2024-07-29 11:28:00
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS h_cpol 15 2024-07-25 12:34:11
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS h_ndc 16 2024-07-29 11:19:05
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_1p5c 17 2024-07-25 12:53:23
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_2c 13 2024-07-25 12:43:06
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem 16 2024-07-29 11:37:30
REMIND-MAgPIE 3.3-4.8 d_delfrag 3 2024-06-28 12:07:47
REMIND-MAgPIE 3.3-4.8 d_strain 3 2024-06-28 12:07:58
REMIND-MAgPIE 3.3-4.8 h_cpol 3 2024-06-28 12:08:08
REMIND-MAgPIE 3.3-4.8 h_ndc 3 2024-06-28 12:08:21
REMIND-MAgPIE 3.3-4.8 o_1p5c 4 2024-06-28 12:08:31
REMIND-MAgPIE 3.3-4.8 o_2c 3 2024-06-28 12:08:41
REMIND-MAgPIE 3.3-4.8 o_lowdem 2 2024-06-28 12:08:51

In [34]:
for (model, scenario), i in release_runs.groupby(["model", "scenario"]):
    print(model, scenario, max(i.version), max(i.create_date))

Damages[GCAM 6.0 NGFS] d_delfrag 4 2024-07-16 23:38:14
Damages[GCAM 6.0 NGFS] d_delfrag_test 1 2024-06-24 13:46:46
Damages[GCAM 6.0 NGFS] d_strain 4 2024-07-16 23:38:19
Damages[GCAM 6.0 NGFS] d_strain_test 1 2024-06-24 13:47:04
Damages[GCAM 6.0 NGFS] h_cpol 4 2024-07-16 23:38:25
Damages[GCAM 6.0 NGFS] h_cpol_test 1 2024-06-24 13:47:23
Damages[GCAM 6.0 NGFS] h_ndc 4 2024-07-16 23:38:31
Damages[GCAM 6.0 NGFS] h_ndc_test 1 2024-06-24 13:47:40
Damages[GCAM 6.0 NGFS] o_1p5c 5 2024-08-23 12:38:48
Damages[GCAM 6.0 NGFS] o_1p5c_test 1 2024-06-24 13:47:58
Damages[GCAM 6.0 NGFS] o_2c 4 2024-07-16 23:38:42
Damages[GCAM 6.0 NGFS] o_2c_test 1 2024-06-24 13:48:16
Damages[GCAM 6.0 NGFS] o_lowdem 5 2024-08-23 12:38:58
Damages[GCAM 6.0 NGFS] o_lowdem_test 1 2024-06-24 13:48:33
Damages[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] d_delfrag 3 2024-07-16 23:38:52
Damages[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] d_strain 3 2024-07-16 23:38:58
Damages[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] h_cpol 3 2024-07-16 23:39:04
Damages[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] h_ndc 3 2024-07-16 23:39:09
Damages[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] o_1p5c 3 2024-07-16 23:39:15
Damages[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] o_2c 3 2024-07-16 23:39:20
Damages[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] o_lowdem 3 2024-07-16 23:39:26
Damages[REMIND-MAgPIE 3.3-4.7] d_delfrag 1 2024-04-17 11:52:18
Damages[REMIND-MAgPIE 3.3-4.7] d_strain 1 2024-04-17 11:52:23
Damages[REMIND-MAgPIE 3.3-4.7] h_cpol 1 2024-04-17 11:52:29
Damages[REMIND-MAgPIE 3.3-4.7] h_ndc 1 2024-04-17 11:52:35
Damages[REMIND-MAgPIE 3.3-4.7] o_1p5c 1 2024-04-17 11:52:41
Damages[REMIND-MAgPIE 3.3-4.7] o_2c 1 2024-04-17 11:52:46
Damages[REMIND-MAgPIE 3.3-4.7] o_lowdem 1 2024-04-17 11:52:52
Damages[REMIND-MAgPIE 3.3-4.8] d_delfrag 3 2024-07-16 23:39:31
Damages[REMIND-MAgPIE 3.3-4.8] d_delfrag_test 1 2024-06-24 13:48:50
Damages[REMIND-MAgPIE 3.3-4.8] d_strain 3 2024-07-16 23:39:36
Damages[REMIND-MAgPIE 3.3-4.8] d_strain_test 1 2024-06-24 13:49:07
Damages[REMIND-MAgPIE 3.3-4.8] h_cpol 3 2024-07-16 23:39:42
Damages[REMIND-MAgPIE 3.3-4.8] h_cpol_test 1 2024-06-24 13:49:24
Damages[REMIND-MAgPIE 3.3-4.8] h_ndc 3 2024-07-16 23:39:47
Damages[REMIND-MAgPIE 3.3-4.8] h_ndc_test 1 2024-06-24 13:49:42
Damages[REMIND-MAgPIE 3.3-4.8] o_1p5c 5 2024-08-23 12:39:06
Damages[REMIND-MAgPIE 3.3-4.8] o_1p5c_test 1 2024-06-24 13:50:00
Damages[REMIND-MAgPIE 3.3-4.8] o_2c 3 2024-07-16 23:39:59
Damages[REMIND-MAgPIE 3.3-4.8] o_2c_test 1 2024-06-24 13:50:17
Damages[REMIND-MAgPIE 3.3-4.8] o_lowdem 3 2024-08-23 12:39:20
Downscaling[GCAM 6.0 NGFS] d_delfrag 6 2024-09-20 13:54:29
Downscaling[GCAM 6.0 NGFS] d_strain 6 2024-09-20 13:55:06
Downscaling[GCAM 6.0 NGFS] h_cpol 7 2024-09-20 13:55:44
Downscaling[GCAM 6.0 NGFS] h_ndc 6 2024-09-20 13:56:23
Downscaling[GCAM 6.0 NGFS] o_1p5c 6 2024-09-20 13:57:00
Downscaling[GCAM 6.0 NGFS] o_2c 6 2024-09-20 13:57:36
Downscaling[GCAM 6.0 NGFS] o_lowdem 7 2024-09-20 13:58:08
Downscaling[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] d_delfrag 4 2024-09-20 14:05:54
Downscaling[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] d_strain 4 2024-09-20 14:06:25
Downscaling[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] h_cpol 5 2024-09-20 14:06:54
Downscaling[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] h_ndc 4 2024-09-20 14:07:21
Downscaling[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] o_1p5c 4 2024-09-20 14:07:50
Downscaling[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] o_2c 4 2024-09-20 14:08:19
Downscaling[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] o_lowdem 5 2024-09-20 14:08:48
Downscaling[REMIND-MAgPIE 3.3-4.7] d_delfrag 3 2024-04-16 13:08:46
Downscaling[REMIND-MAgPIE 3.3-4.7] d_strain 3 2024-04-16 13:09:12
Downscaling[REMIND-MAgPIE 3.3-4.7] h_cpol 3 2024-04-16 13:09:37
Downscaling[REMIND-MAgPIE 3.3-4.7] h_ndc 3 2024-04-16 13:10:02
Downscaling[REMIND-MAgPIE 3.3-4.7] o_1p5c 3 2024-04-16 13:10:28
Downscaling[REMIND-MAgPIE 3.3-4.7] o_2c 3 2024-04-16 13:10:55
Downscaling[REMIND-MAgPIE 3.3-4.7] o_lowdem 3 2024-04-16 13:11:19
Downscaling[REMIND-MAgPIE 3.3-4.8] d_delfrag 3 2024-09-23 16:07:19
Downscaling[REMIND-MAgPIE 3.3-4.8] d_delfrag_d50 2 2024-09-23 16:08:02
Downscaling[REMIND-MAgPIE 3.3-4.8] d_strain 3 2024-09-23 16:08:44
Downscaling[REMIND-MAgPIE 3.3-4.8] h_cpol 5 2024-09-23 16:09:25
Downscaling[REMIND-MAgPIE 3.3-4.8] h_cpol_d50 2 2024-09-23 16:10:05
Downscaling[REMIND-MAgPIE 3.3-4.8] h_ndc 3 2024-09-23 16:10:48
Downscaling[REMIND-MAgPIE 3.3-4.8] h_ndc_d50 2 2024-09-23 16:11:29
Downscaling[REMIND-MAgPIE 3.3-4.8] o_1p5c 4 2024-09-23 16:12:11
Downscaling[REMIND-MAgPIE 3.3-4.8] o_1p5c_d50 2 2024-09-23 16:12:51
Downscaling[REMIND-MAgPIE 3.3-4.8] o_2c 3 2024-09-23 16:13:31
Downscaling[REMIND-MAgPIE 3.3-4.8] o_2c_d50 2 2024-09-23 16:14:12
Downscaling[REMIND-MAgPIE 3.3-4.8] o_lowdem 2 2024-09-23 16:14:51
GCAM 6.0 NGFS d_delfrag 9 2024-06-28 09:30:04
GCAM 6.0 NGFS d_delfrag_test 1 2024-06-21 14:15:31
GCAM 6.0 NGFS d_strain 9 2024-06-28 09:30:21
GCAM 6.0 NGFS d_strain_test 1 2024-06-21 14:15:48
GCAM 6.0 NGFS h_cpol 9 2024-06-28 09:30:38
GCAM 6.0 NGFS h_cpol_stress 2 2024-06-21 07:44:32
GCAM 6.0 NGFS h_cpol_test 1 2024-06-21 14:16:05
GCAM 6.0 NGFS h_ndc 8 2024-06-28 09:30:54
GCAM 6.0 NGFS h_ndc_test 1 2024-06-21 14:16:21
GCAM 6.0 NGFS o_1p5c 9 2024-06-28 09:31:11
GCAM 6.0 NGFS o_1p5c_test 1 2024-06-21 14:16:38
GCAM 6.0 NGFS o_2c 8 2024-06-28 09:31:29
GCAM 6.0 NGFS o_2c_test 1 2024-06-21 14:16:54
GCAM 6.0 NGFS o_lowdem 8 2024-07-12 03:53:54
GCAM 6.0 NGFS o_lowdem_test 1 2024-06-21 14:17:10
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS d_delfrag 13 2024-07-29 11:32:47
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS d_strain 14 2024-07-29 11:28:00
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS h_cpol 15 2024-07-25 12:34:11
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS h_cpol_stress 1 2024-06-21 13:52:50
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS h_ndc 16 2024-07-29 11:19:05
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_1p5c 17 2024-07-25 12:53:23
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_1p5c_test 2 2024-06-24 14:32:59
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_2c 13 2024-07-25 12:43:06
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_2c_test 2 2024-06-24 14:40:34
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_lowdem 16 2024-07-29 11:37:30
NiGEM NGFS v1.24.1GCAM 6.0 NGFS d_delfrag 1 2024-05-15 09:04:11
NiGEM NGFS v1.24.1GCAM 6.0 NGFS d_strain 1 2024-05-15 09:04:20
NiGEM NGFS v1.24.1GCAM 6.0 NGFS h_cpol 1 2024-05-15 09:04:24
NiGEM NGFS v1.24.1GCAM 6.0 NGFS h_ndc 1 2024-05-15 09:04:29
NiGEM NGFS v1.24.1GCAM 6.0 NGFS o_1p5c 1 2024-05-15 09:04:35
NiGEM NGFS v1.24.1GCAM 6.0 NGFS o_2c 1 2024-05-15 09:04:42
NiGEM NGFS v1.24.1MESSAGEix-GLOBIOM 2.0-M-R12-NGFS d_delfrag 1 2024-05-15 09:04:48
NiGEM NGFS v1.24.1MESSAGEix-GLOBIOM 2.0-M-R12-NGFS d_strain 1 2024-05-15 09:04:55
NiGEM NGFS v1.24.1MESSAGEix-GLOBIOM 2.0-M-R12-NGFS h_cpol 1 2024-05-15 09:04:59
NiGEM NGFS v1.24.1MESSAGEix-GLOBIOM 2.0-M-R12-NGFS h_ndc 1 2024-05-15 09:05:03
NiGEM NGFS v1.24.1MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_1p5c 1 2024-05-15 09:05:10
NiGEM NGFS v1.24.1MESSAGEix-GLOBIOM 2.0-M-R12-NGFS o_2c 1 2024-05-15 09:05:16
NiGEM NGFS v1.24.1REMIND-MAgPIE 3.3-4.7 d_delfrag 2 2024-06-06 08:06:18
NiGEM NGFS v1.24.1REMIND-MAgPIE 3.3-4.7 d_strain 2 2024-06-06 08:06:25
NiGEM NGFS v1.24.1REMIND-MAgPIE 3.3-4.7 h_cpol 1 2024-05-15 09:05:32
NiGEM NGFS v1.24.1REMIND-MAgPIE 3.3-4.7 h_cpol_stress 1 2024-05-15 09:05:35
NiGEM NGFS v1.24.1REMIND-MAgPIE 3.3-4.7 h_ndc 1 2024-05-15 09:05:39
NiGEM NGFS v1.24.1REMIND-MAgPIE 3.3-4.7 o_1p5c 1 2024-05-15 09:05:45
NiGEM NGFS v1.24.1REMIND-MAgPIE 3.3-4.7 o_2c 1 2024-05-15 09:05:52
NiGEM NGFS v1.24.2[GCAM 6.0 NGFS] d_delfrag 1 2024-07-15 18:17:15
NiGEM NGFS v1.24.2[GCAM 6.0 NGFS] d_strain 1 2024-07-15 18:17:24
NiGEM NGFS v1.24.2[GCAM 6.0 NGFS] forecast baseline 1 2024-07-16 17:14:43
NiGEM NGFS v1.24.2[GCAM 6.0 NGFS] h_cpol 1 2024-07-15 18:17:29
NiGEM NGFS v1.24.2[GCAM 6.0 NGFS] h_ndc 1 2024-07-15 18:17:34
NiGEM NGFS v1.24.2[GCAM 6.0 NGFS] o_1p5c 1 2024-07-15 18:17:41
NiGEM NGFS v1.24.2[GCAM 6.0 NGFS] o_2c 1 2024-07-15 18:17:47
NiGEM NGFS v1.24.2[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] d_delfrag 1 2024-07-15 18:12:07
NiGEM NGFS v1.24.2[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] d_strain 1 2024-07-15 18:12:17
NiGEM NGFS v1.24.2[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] forecast baseline 1 2024-07-16 17:14:46
NiGEM NGFS v1.24.2[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] h_cpol 1 2024-07-15 18:12:21
NiGEM NGFS v1.24.2[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] h_ndc 1 2024-07-15 18:12:27
NiGEM NGFS v1.24.2[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] o_1p5c 2 2024-07-17 09:26:00
NiGEM NGFS v1.24.2[MESSAGEix-GLOBIOM 2.0-M-R12-NGFS] o_2c 1 2024-07-15 18:12:33
NiGEM NGFS v1.24.2[REMIND-MAgPIE 3.3-4.8] d_delfrag 2 2024-07-29 09:17:56
NiGEM NGFS v1.24.2[REMIND-MAgPIE 3.3-4.8] d_strain 2 2024-07-29 09:18:13
NiGEM NGFS v1.24.2[REMIND-MAgPIE 3.3-4.8] forecast baseline 1 2024-07-16 17:14:49
NiGEM NGFS v1.24.2[REMIND-MAgPIE 3.3-4.8] h_cpol 1 2024-07-29 09:18:21
NiGEM NGFS v1.24.2[REMIND-MAgPIE 3.3-4.8] h_ndc 2 2024-07-29 09:18:30
NiGEM NGFS v1.24.2[REMIND-MAgPIE 3.3-4.8] o_1p5c 3 2024-07-29 09:18:41
NiGEM NGFS v1.24.2[REMIND-MAgPIE 3.3-4.8] o_2c 2 2024-07-29 09:18:52
REMIND-MAgPIE 3.3-4.7 d_delfrag 10 2024-06-10 16:37:43
REMIND-MAgPIE 3.3-4.7 d_strain 10 2024-06-10 16:37:54
REMIND-MAgPIE 3.3-4.7 h_cpol 10 2024-06-10 16:38:03
REMIND-MAgPIE 3.3-4.7 h_ndc 10 2024-06-10 16:38:14
REMIND-MAgPIE 3.3-4.7 o_1p5c 10 2024-06-10 16:38:24
REMIND-MAgPIE 3.3-4.7 o_2c 10 2024-06-10 16:38:35
REMIND-MAgPIE 3.3-4.7 o_lowdem 10 2024-06-10 16:38:45
REMIND-MAgPIE 3.3-4.8 d_delfrag 3 2024-06-28 12:07:47
REMIND-MAgPIE 3.3-4.8 d_delfrag_d50 1 2024-07-18 09:07:33
REMIND-MAgPIE 3.3-4.8 d_delfrag_test 1 2024-06-21 13:44:25
REMIND-MAgPIE 3.3-4.8 d_strain 3 2024-06-28 12:07:58
REMIND-MAgPIE 3.3-4.8 d_strain_d50 1 2024-07-18 09:07:45
REMIND-MAgPIE 3.3-4.8 d_strain_test 1 2024-06-21 13:44:37
REMIND-MAgPIE 3.3-4.8 h_cpol 3 2024-06-28 12:08:08
REMIND-MAgPIE 3.3-4.8 h_cpol_d50 1 2024-07-18 09:07:55
REMIND-MAgPIE 3.3-4.8 h_cpol_test 1 2024-06-21 13:44:46
REMIND-MAgPIE 3.3-4.8 h_ndc 3 2024-06-28 12:08:21
REMIND-MAgPIE 3.3-4.8 h_ndc_d50 1 2024-07-18 09:08:05
REMIND-MAgPIE 3.3-4.8 h_ndc_test 1 2024-06-21 13:44:58
REMIND-MAgPIE 3.3-4.8 o_1p5c 4 2024-06-28 12:08:31
REMIND-MAgPIE 3.3-4.8 o_1p5c_d50 1 2024-07-18 09:08:15
REMIND-MAgPIE 3.3-4.8 o_1p5c_test 2 2024-06-26 13:18:25
REMIND-MAgPIE 3.3-4.8 o_2c 3 2024-06-28 12:08:41
REMIND-MAgPIE 3.3-4.8 o_2c_d50 1 2024-07-18 09:08:26
REMIND-MAgPIE 3.3-4.8 o_2c_test 1 2024-06-21 13:45:19
REMIND-MAgPIE 3.3-4.8 o_lowdem 2 2024-06-28 12:08:51
REMIND-MAgPIE 3.3-4.8 o_lowdem_d50 1 2024-07-18 09:08:36
REMIND-MAgPIE 3.3-4.8 o_lowdem_test 1 2024-06-28 07:16:03
[Integrated Damages Downscaling]REMIND-MAgPIE 3.3-4.8 d_delfrag_d50 2 2024-08-23 05:50:50
[Integrated Damages Downscaling]REMIND-MAgPIE 3.3-4.8 h_cpol_d50 2 2024-08-23 05:50:54
[Integrated Damages Downscaling]REMIND-MAgPIE 3.3-4.8 h_ndc_d50 2 2024-08-23 05:50:57
[Integrated Damages Downscaling]REMIND-MAgPIE 3.3-4.8 o_1p5c_d50 2 2024-08-23 05:50:59
[Integrated Damages Downscaling]REMIND-MAgPIE 3.3-4.8 o_2c_d50 2 2024-08-23 05:51:02

In [56]:
for (model, scenario), i in release_runs.groupby(["model", "scenario"]):
    if model in ["REMIND-MAgPIE 3.3-4.8"]: #["GCAM 6.0 NGFS", "MESSAGEix-GLOBIOM 2.0-M-R12-NGFS", "REMIND-MAgPIE 3.3-4.8"]:
        if scenario in scenario_mapping.keys():
            try:
                version=max(i.version)
                df = connection.query(model=model, scenario=scenario, version=version)
                df.meta.drop(columns="version", inplace=True)
                df.rename(scenario=scenario_mapping, inplace=True)
                df.to_excel(f"raw/NGFS/{model.replace(" ", "_")}-{scenario}-{version}.xlsx")
                print(f"Downloaded {model} - {scenario} - {version}")
            except:
                print(f"Failed {model} - {scenario} - {version}")

9
Downloaded GCAM 6.0 NGFS - d_delfrag
9
Downloaded GCAM 6.0 NGFS - d_strain
9
Downloaded GCAM 6.0 NGFS - h_cpol
8
Downloaded GCAM 6.0 NGFS - h_ndc
9
Downloaded GCAM 6.0 NGFS - o_1p5c
8
Downloaded GCAM 6.0 NGFS - o_2c
8
Downloaded GCAM 6.0 NGFS - o_lowdem
13
Downloaded MESSAGEix-GLOBIOM 2.0-M-R12-NGFS - d_delfrag
14
Downloaded MESSAGEix-GLOBIOM 2.0-M-R12-NGFS - d_strain
15
Downloaded MESSAGEix-GLOBIOM 2.0-M-R12-NGFS - h_cpol
16
Downloaded MESSAGEix-GLOBIOM 2.0-M-R12-NGFS - h_ndc
17
Downloaded MESSAGEix-GLOBIOM 2.0-M-R12-NGFS - o_1p5c
13
Downloaded MESSAGEix-GLOBIOM 2.0-M-R12-NGFS - o_2c
16
Downloaded MESSAGEix-GLOBIOM 2.0-M-R12-NGFS - o_lowdem
3
Downloaded REMIND-MAgPIE 3.3-4.8 - d_delfrag
3
Downloaded REMIND-MAgPIE 3.3-4.8 - d_strain
3
Downloaded REMIND-MAgPIE 3.3-4.8 - h_cpol
3
Downloaded REMIND-MAgPIE 3.3-4.8 - h_ndc
4
Downloaded REMIND-MAgPIE 3.3-4.8 - o_1p5c
3
Downloaded REMIND-MAgPIE 3.3-4.8 - o_2c
2
Downloaded REMIND-MAgPIE 3.3-4.8 - o_lowdem